# fly.toml app configuration file generated for morning-forest-1907 on 2023-07-14T18:55:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-forest-1907"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
